export const ETH_MAINNET_API_URL = 'https://api.etherscan.io/api';
export const BSC_MAINNET_API_URL = 'https://api.bscscan.com/api';
export const ETH_MAINNET_PLORER_API_URL = 'https://api.ethplorer.io/';
export const CMC_ENDPOINT = 'https://3rdparty-apis.coinmarketcap.com/v1/cryptocurrency/contract?address='
export const CG_ENDPOINT = 'https://api.coingecko.com/api/v3/';
export const PC_PAIRS = "https://api.thegraph.com/subgraphs/name/pancakeswap/pairs";
export const SH_PAIRS = "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2";
export const LLAMA_ENDPOINT = "https://coins.llama.fi/";
export const BLOCKS_CLIENT = "https://api.thegraph.com/subgraphs/name/pancakeswap/blocks";
export const INFO_CLIENT = 'https://bsc.streamingfast.io/subgraphs/name/pancakeswap/exchange-v2';
export const BITQUERY_ENDPOINT = "https://graphql.bitquery.io";
export const NODREAL_BSC_ENDPOINT = "https://bsc-mainnet.nodereal.io/v1/";
export const NODREAL_ETH_ENDPOINT = "https://eth-mainnet.nodereal.io/v1/";

export const ETHPLORER_API_KEY = 'EK-32KDR-3MoJfLq-QoUAU';
export const BITQUERY_API_KEY = 'BQYOlzIJkKcaiJFbq1u8GrBCLxbkBB1G';
export const COINMARKETCAP_API_KEY = 'd27ab07a-3853-4402-8d56-651767ba4da5';
export const ETHERSCAN_API_KEY = 'DF8U1AYKKAW8NHQQJ2H34W6B49H38JI9SU';
export const BSCSCAN_API_KEY = '9JXFSN6Y82GSADZZRHHNDD29AMYFMB7XYS';
export const NODEREAL_BSC_API_KEY = '62368f2c5ac94dc59139d5b255ba1adb';
export const NODEREAL_ETH_API_KEY = '795d186712b74cd6b2f17f0db0b2db7b';